idf_component_register(
    SRCS
        "app_main.cpp"
        "../src/esp_idf_file_store.cpp"
        "../src/esp_idf_sd_card.cpp"
        "../src/esp_idf_epaper.cpp"
        "../src/esp_idf_buttons.cpp"
        "../src/esp_idf_power_service.cpp"
        "../src/epaper_refresh_service.cpp"
        "../src/esp_idf_platform.cpp"
        "../../../src/render/owned_mono_framebuffer.cpp"
        "../../../src/runtime/input_runtime.cpp"
    INCLUDE_DIRS
        "../include"
        "../../../include"
    REQUIRES
        driver
        esp_timer
        esp_hw_support
        fatfs
        sdmmc
)
